### ISSUE TITLE
建議調整「配」「和」

### ISSUE THREAD

**Issue by jeffchang-gitgit** [max32002/TaiwanPearl#3]
因為拔腳產生左右不平衡的狀態
如附圖
![1599707843271](https://user-images.githubusercontent.com/71055478/92679012-de927300-f359-11ea-8d03-ce3193b3702b.jpg)

**Comment by max32002** [comment]
![Screen Shot 2020-09-10 at 23 35 59](https://user-images.githubusercontent.com/4498233/92755469-6f029f00-f3be-11ea-8945-a1f5001dbfb5.png)
* 調好了，請重新下載 ver 2.100 版。
* 我看不出來「和」有不平衡的問題。

**Comment by max32002** [comment]
發現新的版本，有新的問題，酉裡的一，沒套到效果。

**Comment by max32002** [comment]
![Screen Shot 2020-09-11 at 00 30 47](https://user-images.githubusercontent.com/4498233/92763404-146d4100-f3c6-11ea-9373-2786c6997ce8.png)
調整好了，請重下 ver 2.102 版。

**Comment by jeffchang-gitgit** [comment]
👍👍
